### ISSUE TITLE
Port BaseContract 

### ISSUE THREAD

**Issue by logohere** [zapproject/jzap#28]
## Summary 
Port BaseContract into java

### Reference 
https://github.com/zapproject/zap-monorepo/blob/5edea2aa8df7312ea5ac560eb083ece22d042359/packages/BaseContract/src/index.ts#L10

### Definition of done
Async GetContract & GetContractOwner are testable

**Comment by Jonathan-Eid** [comment]
#### Definition of Done Cont'd

1. Copy files from target/class/io...zapproject/jzap/wrappers to src/main/java/io...github/wrappers

2. Create an abstract java class called BaseContract that extends the 
org.web3j.Contract object:

https://javadoc.io/doc/org.web3j/core/latest/org/web3j/tx/Contract.html

3. The additional functionality will include the logic from the BaseContract.js found in the ZapJS monorepo:

https://github.com/zapproject/zap-monorepo/blob/master/packages/BaseContract/src/index.ts

4.  Switch out the Contract inheritance found in all the classes in the src/main/java/io...github/wrappers folder with the newly created BaseContract
