### ISSUE TITLE
Extension of BaseContract as Arbiter 

### ISSUE THREAD

**Issue by logohere** [zapproject/jzap#31]
## Summary
Extension of BaseContract as Arbiter 

## Reference 
https://github.com/zapproject/zap-monorepo/blob/5edea2aa8df7312ea5ac560eb083ece22d042359/packages/Arbiter/src/index.ts

## Definition of done
Properly imported and instantiated

**Comment by taejoonn** [comment]
Working on Arbiter wrapper.
